

service: docker-Thumbnails # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  profile: serverless-admin
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
  environment:
    Image_size: "128"
custom:
  bucket: bucket-demo-thumb
  pythonRequirements:
    dockerizePip: true

functions:
  generate_image_s3:
    handler: handler.generate_image_s3
    events:
      - s3:
          bucket: $.{self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
resources:
  Resources:
    bucketdemothumb:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.stage}
# Resources:
#       S3Bucket:
#         Type: AWS::S3::Bucket
#         Properties:
#           BucketName: "${self:service}-${opt:stage, self:provider.stage}"
#           BucketEncryption:
#             ServerSideEncryptionConfiguration:
#               - ServerSideEncryptionByDefault:
#                   SSEAlgorithm: 'aws:kms'
#                   KMSMasterKeyID: "aws:kms:${self:provider.region}:#{AWS::AKIAJMAXE6O2XBRWPUDA}:xFZCtXG8t8eiGCNP/NYJoEx0CrWjo0Yl9WqhvX6W/${self:custom.kms.${self:provider.stage}}"

plugins:
  - serverless-python-requirements
